### ISSUE TITLE
Thread context for IRQs

### ISSUE THREAD

**Issue by joekoolade** [joekoolade/JOE#12]
Interrupts operate in the context of the thread they interrupt. Plan is switch interrupt to their own thread which will provide a stack and memory allocation

**Comment by SamarthGoyal007** [comment]
A team of 3 other UT Austin CS students along with me would like to work on this issue for our Virtualization class!

**Comment by joekoolade** [comment]
I would welcome the help. I have not been able to give my project the attention it needs.

**Comment by joekoolade** [comment]
Not going to do this. Does not provide any apparent advantages.
