### ISSUE TITLE
Consider a switch to SubstrateVM?

### ISSUE THREAD

**Issue by mikehearn** [joekoolade/JOE#8]
Jikes is cool but it seems the spiritual successor is SubstrateVM. It can do AOT compilation, dead code elimination, closed-world optimisations and uses hardly any memory. No dynamic code loading though and not perfectly Java compatible.

It's probably a much better foundation to build on though especially because with it, you can run other languages that are not just Java. For instance you could run xonsh as a basic shell, inside a GraalPython sandbox, all inside the same JVM process.

**Comment by joekoolade** [comment]
SubstrateVM seems very capable but the JikesRVM is better suited to my design goals for JOE. Those goals are a simplified tool chain, everything done in Java, networked class loading, and the ability to self host the JikesRVM and tools.
